version: "2"

services:
  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379
  watcher:
    build: ./
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REDIS_URI=redis://redis:6379
  command:
    image: redis:5.0-alpine
    command: ["/bin/sh", "-c", "echo 'Open http://127.0.0.1:8080/metrics' && while [ true ]; do redis-cli -u redis://redis:6379 hgetall 'my_executed_keys' && sleep 1; done"]
    depends_on:
      - watcher